const SB='https://poqbvrffqclrxbxgoxlz.supabase.co', KEY='sb_publishable_jWkqGg3IW-6G-D92CXR43A_rPZBSMxk', WA='558396386173';
const S={products:[],settings:null,neighborhoods:[],banners:[],session:JSON.parse(localStorage.getItem('dl_session')||'null'),profile:null,cart:JSON.parse(localStorage.getItem('dl_cart')||'{}'),favorites:new Set(),orders:[],adminTab:'dashboard',admin:{orders:[],profiles:[],products:[],neighborhoods:[],schedule:[],coupons:[],banners:[],audit:[],cartAdds:[]}};
const root=document.getElementById('root'), drawer=document.getElementById('drawer'), overlay=document.getElementById('overlay'), modal=document.getElementById('modal');
function money(c){return (Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function digits(v){return String(v||'').replace(/\D/g,'')}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function fmtCpf(v){let d=digits(v).slice(0,11);return d.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')}function maskCpf(v){let d=digits(v);return d.length===11?`***.${d.slice(3,6)}.***-**`:'—'}function fmtPhone(v){let d=digits(v).replace(/^55/,'').slice(0,11);return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:v||'—'}function normPhone(v){let d=digits(v);if(d.startsWith('55')&&d.length>11)d=d.slice(2);if(d.length!==11||d[2]!=='9')return null;let dd=+d.slice(0,2);if(dd<11||dd>99)return null;return '55'+d}function validCpf(v){let c=digits(v);if(c.length!==11||/^(\d)\1{10}$/.test(c))return false;for(let t=9;t<11;t++){let s=0;for(let i=0;i<t;i++)s+=(+c[i])*(t+1-i);let r=(s*10)%11;if(r===10)r=0;if(r!==+c[t])return false}return true}function techEmail(phone){return `${phone}@cliente.donnala.app`}function route(){return location.hash.replace(/^#/,'')||'/'}function go(p){location.hash=p}function saveCart(){localStorage.setItem('dl_cart',JSON.stringify(S.cart));updateCartBadge()}function cartCount(){return Object.values(S.cart).reduce((a,x)=>a+x,0)}function pById(id){return S.products.find(p=>p.id===id)}function cartSubtotal(){return Object.entries(S.cart).reduce((a,[id,q])=>{let p=pById(id);return a+(p?.price_cents||0)*q},0)}
async function api(path,{method='GET',body,token,headers={}}={}){let h={apikey:KEY,...headers};if(token)h.Authorization='Bearer '+token;if(body!==undefined)h['Content-Type']='application/json';let r=await fetch(SB+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});let txt=await r.text(),data=null;try{data=txt?JSON.parse(txt):null}catch{data=txt}if(!r.ok)throw new Error(data?.message||data?.msg||data?.error_description||data?.error||txt||('Erro '+r.status));return data}
async function auth(path,body,method='POST',token){return api('/auth/v1'+path,{method,body,token})}
async function loadPublic(){try{let [p,s,n,b]=await Promise.all([api('/rest/v1/products?select=*&active=eq.true&order=category.asc,sort_order.asc'),api('/rest/v1/app_settings?select=*&id=eq.true&limit=1'),api('/rest/v1/neighborhoods?select=*&active=eq.true&order=sort_order.asc,name.asc'),api('/rest/v1/banners?select=*&active=eq.true&order=sort_order.asc')]);S.products=p||[];S.settings=s?.[0]||null;S.neighborhoods=n||[];S.banners=b||[]}catch(e){console.error(e);toast('Não foi possível carregar o catálogo: '+e.message,'err')}}
async function loadProfile(){if(!S.session?.user?.id){S.profile=null;S.favorites=new Set();return}try{let p=await api('/rest/v1/profiles?select=user_id,full_name,cpf,phone,role,must_change_password&user_id=eq.'+S.session.user.id,{token:S.session.access_token});S.profile=p?.[0]||null;let f=await api('/rest/v1/favorites?select=product_id&user_id=eq.'+S.session.user.id,{token:S.session.access_token});S.favorites=new Set((f||[]).map(x=>x.product_id))}catch(e){console.error(e)}}
async function loadOrders(){if(!S.session)return;try{S.orders=await api('/rest/v1/orders?select=*,order_items(*)&user_id=eq.'+S.session.user.id+'&order=created_at.desc',{token:S.session.access_token})||[]}catch(e){S.orders=[]}}
function setSession(x){S.session=x||null;if(x)localStorage.setItem('dl_session',JSON.stringify(x));else localStorage.removeItem('dl_session')}
async function logout(){try{if(S.session)await auth('/logout',{},'POST',S.session.access_token)}catch{}setSession(null);S.profile=null;S.favorites=new Set();go('/');render()}
async function maybeRefresh(){if(!S.session?.refresh_token)return;let exp=S.session.expires_at||0;if(Date.now()/1000<exp-60)return;try{let d=await auth('/token?grant_type=refresh_token',{refresh_token:S.session.refresh_token});setSession(d);await loadProfile()}catch{setSession(null)}}
function header(){let acct=S.profile?'/minha-conta':'/entrar';return `<div class="topbar">10% na primeira compra com <b>PRIMEIRA10</b> • Pedidos pelo WhatsApp</div><header class="header"><div class="nav"><a class="brand" href="#/">Donnalá<small>TORTAS SALGADAS</small></a><nav class="navlinks"><a class="hideMob" href="#/catalogo">Cardápio</a>${S.profile?.role==='admin'?'<a class="hideMob" href="#/admin">Admin</a>':''}<a class="iconbtn" href="#${acct}">${S.profile?'Minha conta':'Entrar'}</a><button class="iconbtn" onclick="openCart()">Sacola <span id="cartBadge" class="badgeCount">${cartCount()}</span></button></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="inner"><div><div class="brand" style="color:#fff">Donnalá</div><p>Tortas salgadas artesanais, feitas sob encomenda.</p></div><div><b>Atendimento</b><p><a href="https://wa.me/${WA}" target="_blank">WhatsApp: ${fmtPhone(WA)}</a></p><p><a href="#/politica-de-privacidade">Política de Privacidade</a></p></div><div><b>Administração</b><p><a href="#/admin/login">Acesso administrativo</a></p></div></div></footer><a class="whats" target="_blank" aria-label="WhatsApp" href="https://wa.me/${WA}">◔</a>`}
function updateCartBadge(){let e=document.getElementById('cartBadge');if(e)e.textContent=cartCount()}
function toast(msg,type=''){let n=document.createElement('div');n.className='notice '+type;n.textContent=msg;n.style.cssText='position:fixed;z-index:200;right:18px;top:18px;max-width:420px;box-shadow:var(--shadow)';document.body.appendChild(n);setTimeout(()=>n.remove(),3800)}
function filteredProducts(cat){let arr=S.products.filter(p=>p.category===cat);if(S.settings?.hide_unavailable)arr=arr.filter(p=>p.in_stock);return arr}
function productCard(p){let fav=S.favorites.has(p.id);return `<article class="card"><div class="productImage" style="background-image:url('${esc(p.image_url||'https://donnala-tortas.hellensgaldino.chatgpt.site/images/encomendas-tortas-inteiras.jpeg')}')"></div><div class="cardBody"><div class="chiprow">${p.featured?'<span class="chip gold">Mais pedido</span>':''}${p.tag?`<span class="chip">${esc(p.tag)}</span>`:''}${!p.in_stock?'<span class="chip gray">Esgotado</span>':''}</div><div class="productTitle"><h3>${esc(p.name)}</h3><button class="fav ${fav?'on':''}" onclick="toggleFav('${p.id}')">♥</button></div><p class="muted">${esc(p.description||'')}</p><div class="price">${money(p.price_cents)}</div><button class="btn btn-primary" ${!p.in_stock?'disabled style="opacity:.5"':''} onclick="addCart('${p.id}')">${p.in_stock?'Adicionar à sacola':'Indisponível'}</button></div></article>`}
function catalog(cat='fatias'){let cats=[['fatias','Fatias'],['tortas','Tortas completas'],['bebidas','Bebidas']];return `<section id="catalogo" class="section"><span class="eyebrow" style="color:var(--wine)">CARDÁPIO</span><h2>Escolha seu sabor</h2><p class="sectionLead">Produção artesanal, recheio generoso e receitas com identidade nordestina.</p><div class="tabs">${cats.map(([k,l])=>`<button class="tab ${cat===k?'active':''}" onclick="renderCatalog('${k}')">${l}</button>`).join('')}</div><div id="productGrid" class="grid">${filteredProducts(cat).map(productCard).join('')||'<div class="empty">Nenhum produto disponível.</div>'}</div></section>`}
function renderCatalog(cat){document.getElementById('productGrid').innerHTML=filteredProducts(cat).map(productCard).join('')||'<div class="empty">Nenhum produto disponível.</div>';document.querySelectorAll('.tab').forEach((x,i)=>x.classList.toggle('active',['fatias','tortas','bebidas'][i]===cat))}
function home(){let banner=S.banners.find(b=>{let d=new Date().toISOString().slice(0,10);return (!b.starts_at||b.starts_at<=d)&&(!b.ends_at||b.ends_at>=d)});return `${header()}<main><section class="hero"><div class="inner"><span class="eyebrow">TORTAS SALGADAS ARTESANAIS</span><h1>A queridinha do Maior São João do Mundo, agora, na sua mesa!</h1><p>Receitas autorais, sabor nordestino e tortas feitas à mão para transformar qualquer encontro.</p><div class="actions"><a class="btn btn-light" href="#/catalogo">Escolher minha fatia</a><button class="btn btn-gold" onclick="openCart()">Ver minha sacola</button></div></div></section>${banner?`<section class="section slim"><div class="panel row between wrap"><div><b class="eyebrow" style="color:var(--wine)">NOVIDADE</b><h3 style="margin:6px 0">${esc(banner.title)}</h3><span class="muted">${esc(banner.subtitle||'')}</span></div>${banner.cta_label?`<a class="btn btn-primary" href="${esc(banner.cta_url||'#/catalogo')}">${esc(banner.cta_label)}</a>`:''}</div></section>`:''}${catalog('fatias')}<section class="section"><span class="eyebrow" style="color:var(--wine)">COMO FUNCIONA</span><h2>Seu pedido em 3 passos</h2><div class="featureStrip"><div class="feature"><b>01</b><h3>Escolha</h3><p class="muted">Monte sua sacola com fatias, tortas completas e bebidas.</p></div><div class="feature"><b>02</b><h3>Agende</h3><p class="muted">Selecione retirada ou entrega e a data desejada.</p></div><div class="feature"><b>03</b><h3>Confirme</h3><p class="muted">O pedido é registrado e enviado para confirmação no WhatsApp.</p></div></div></section></main>${footer()}`}
function pageWrap(content){return `${header()}<main>${content}</main>${footer()}`}
